//
// Created by fjulian on 23.07.20.
//

#ifndef TYPING_8_LIFTCONTROLLERCARTESIANIMPEDANCE_H
#define TYPING_8_LIFTCONTROLLERCARTESIANIMPEDANCE_H


class LiftControllerCartesianImpedance {

};


#endif //TYPING_8_LIFTCONTROLLERCARTESIANIMPEDANCE_H
